import MainNav from "@/components/MainNav";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/assets/globals.css";

const geistSans = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} mx-auto max-w-[1440px] antialiased min-h-dvh grid`}
      >
        {children}
      </body>
    </html>
  );
}
