import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../assets/globals.css";
import MainNav from "@/components/MainNav";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
